<?php
header('Content-Type: text/html; charset=utf-8');

$names = array('Jesusa Wakeman', 'Glinda Robey', 'Lesley Willard', 'Sulema Beaumont', 'Joy Greening', 'Nerissa Milam', 'Roxana Vanwagoner', 'Ligia Angel', 'Margurite Vinci', 'Melva Overturf', 'Eula Kilbane', 'Hiedi Pedrick', 'Israel Gove', 'Carlyn Walworth', 'Avril Moncayo', 'Prince Kerwin', 'Veronika Kenner', 'Laticia Mends', 'Thad Brunner', 'Ebonie Kennerly', 'Rea Harbin', 'Dagny Ashman', 'Chong Rollo', 'Cora Boldt', 'Ana Dion', 'Alethea Crosswell', 'Rolanda Scales', 'Shela Whitfield', 'Josefa Bordeau', 'Angle Medal', 'Raquel Riggle', 'Shenna Klar', 'Ozell Lamar', 'Darryl Medford', 'Harris Spivey', 'Zulema Callison', 'Martha Cai', 'Stewart Twining', 'Else Marshall', 'Margery Shufelt', 'Earleen Heidelberg', 'Chana Cover', 'Rosalie Dieterich', 'Alvera Tietjen', 'Janessa Merz', 'Gabriel Dorner', 'Zandra Mcandrew', 'Sharen Burkholder', 'Idalia Rousselle', 'Stephaine Sheffield', 'Garth Karls', 'Teisha Tanouye', 'Trudie Glickman', 'Annetta Rule', 'Chasity Wilkison', 'Aldo Podesta', 'Alfredia Crites', 'Truman Ezzell', 'Thao Clayson', 'Wm Pillow', 'Aurea Venters', 'Liberty Plank', 'Doretha Lynd', 'Bridget Seefeldt', 'Tran Kammer', 'Kimberly Perkinson', 'Denyse Germano', 'Noelle Reitzel', 'Jamika Monsen', 'Ladonna Elser', 'Eboni Muirhead', 'Jolanda Gheen', 'Yevette Mowrer', 'Junita Wittenberg', 'Anne Bibler', 'Lorrie Baine', 'Shaunte Brodeur', 'Damien Platero', 'Adelia Ostrowski', 'Herta Buechler', 'Shawana Damiano', 'Kasi Gloria', 'Coretta Milum', 'Coral Cargo', 'Rosena Malcomb', 'Pablo Brashear', 'Lena Uber', 'Belen Sedlacek', 'Olive Faucette', 'Karmen Stiner', 'Krystyna Antos', 'Aja Dines', 'Jolene Carreno', 'Abigail Wilde', 'Leif Roof', 'Palmira Rase', 'Dustin Karg', 'Audra Demoura', 'Lisa Plath', 'Stacey Woodworth', 'Ambrose Ralls', 'Dayle Mckissack', 'Annalee Hudkins', 'Reagan Cushman', 'Santina Pounders', 'Olga Devitt', 'Ronny Watkins', 'Cindie Waymire', 'Joe Zellmer', 'Fidela Denker', 'Lacresha Guidroz', 'Ignacia Perna', 'Angel Shams', 'Francis Pontes', 'Zana Dogan', 'Rosanne Mcneill', 'Shera Raynes', 'Eldon Oberholtzer', 'Jenell Watrous', 'Tennille Furr', 'Bernie Weitzel', 'Nicholas Leet', 'Patrica Garlitz', 'Ashanti Tabler', 'Vennie Grinstead', 'Maude Zirbel', 'Lilliana Moores', 'Camille Budge', 'Mirtha Midgett', 'Lacie Stansberry', 'Lorena Reppert', 'Antonetta Schrick', 'Anika Rager', 'In Rodriquez', 'Juliana Heard', 'Tu Vawter', 'Yasmine Shinkle', 'Elke Ferrara', 'Noelle Tibbles', 'Annabell Fellers', 'Minerva Concepcion', 'Taneka Ammann', 'Magdalen Brink', 'Neta Eidson', 'Nona Burden', 'Julian Hartl', 'Leonie Creighton', 'Mistie Benfer', 'Blythe Pizana', 'Katie Heckstall');

$roles = array('Réalisateur', 'Acteur', 'Acteur', 'Acteur', 'Acteur', 'Acteur', 'Acteur', 'Acteur', 'Acteur', 'Son', 'Scénariste', 'Cascadeur', 'Maquillage', 'Scripte', 'Électro', 'Régisseur', 'Repéreur');

for($i = 0; $i <= 400; $i++){
	for($j = 0; $j <= 10; $j++){
		echo "INSERT INTO `lumiere`.`collaborators`(`id`, `movie`, `name`, `role`) VALUES (NULL, " . $i . ", '" . $names[rand(0, count($names) - 1)] . "', '" . $roles[rand(0, count($roles) - 1)] . "');"; echo '<br>';
	}
}